version: 3

vars:
  VERSION: v0.5.0
  BIN_DIR: "bin"

tasks:
  build:
    desc: "Build"
    sources:
      - ./*.go
      - ./examples/**/*.go
    generates:
      - "{{.BIN_DIR}}/main"
      - "{{.BIN_DIR}}/persistence"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/main ./examples/main
      - go build -o {{.BIN_DIR}}/persistence ./examples/persistence

  clean:
    desc: "Clean"
    cmds:
      - "rm -rf {{.BIN_DIR}}/main"
      - "rm -rf {{.BIN_DIR}}/persistence"

  test:
    desc: "Run tests"
    cmds:
      - go test -v -race ./test

  tag:
    desc: "タグを更新する"
    deps:
      - build
    cmds:
      - git tag {{.VERSION}}
      - git tag

  default:
    cmds:
      - task --list

