version: 3

vars:
  VERSION: v0.2.0
  BIN_NAME: "do-test"
  BIN_DIR: "bin"
  BIN_PATH: "{{.BIN_DIR}}/{{.BIN_NAME}}"
  DB_NAME: "{{.BIN_NAME}}.json"

tasks:
  build:
    desc: "Build"
    sources:
      - ./*.go
      - ./examples/*.go
    generates:
      - "{{.BIN_PATH}}"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_PATH}} ./examples

  clean:
    desc: "Clean"
    cmds:
      - "rm -rf {{.BIN_PATH}} {{.DB_NAME}}"

  test:
    desc: "Run tests"
    cmds:
      - go test -v -race ./test

  tag:
    desc: "タグを更新する"
    deps:
      - build
    cmds:
      - git tag {{.VERSION}}
      - git tag

  default:
    cmds:
      - task --list

